/*
 * This java source file is generated by DAO4J v1.16
 * Generated on Fri Mar 20 11:39:50 IST 2009
 * For more information, please contact b-i-d@163.com
 * Please check http://members.lycos.co.uk/dao4j/ for the latest version.
 */

package com.adams.dt.pojo;

import java.io.Serializable; 

/*
 * For Table groups
 */
public class Modules implements Serializable {
	 
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	  /* group_ID, PK */
    protected int moduleId;

    /* group_label */
    protected String moduleName;
    protected int moduleY;
    protected int moduleWidth;
	public int getModuleId() {
		return moduleId;
	}
	public void setModuleId(int moduleId) {
		this.moduleId = moduleId;
	}
	public String getModuleName() {
		return moduleName;
	}
	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}
	public int getModuleY() {
		return moduleY;
	}
	public void setModuleY(int moduleY) {
		this.moduleY = moduleY;
	}
	public int getModuleWidth() {
		return moduleWidth;
	}
	public void setModuleWidth(int moduleWidth) {
		this.moduleWidth = moduleWidth;
	}
 
}