/*
 * This java source file is generated by DAO4J v1.16
 * Generated on Fri Mar 20 11:39:57 IST 2009
 * For more information, please contact b-i-d@163.com
 * Please check http://members.lycos.co.uk/dao4j/ for the latest version.
 */

package com.adams.dt.pojo;

import java.io.Serializable;   
import java.util.Set;
/*
 * For Table chat
 */
public class Report implements Serializable{

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;	
    
	protected int reportId;
	protected String reportName;
	protected Column stackBarCol;     
	protected Column pieChartCol; 
	protected String stackBarName;
	protected String pieChartName;
	protected String projectStatus;
	protected int profileFk;
	protected Set<Column> columnSet;   
    public Set<Column> getColumnSet() {
		return columnSet;
	}

	public void setColumnSet(Set<Column> columnSet) {
		this.columnSet = columnSet;
	}

	public Report() {
    }

	public int getReportId() {
		return reportId;
	}

	public void setReportId(int reportId) {
		this.reportId = reportId;
	}

	public String getReportName() {
		return reportName;
	}

	public void setReportName(String reportName) {
		this.reportName = reportName;
	}
 

	public Column getStackBarCol() {
		return stackBarCol;
	}

	public void setStackBarCol(Column stackBarCol) {
		this.stackBarCol = stackBarCol;
	}

	public Column getPieChartCol() {
		return pieChartCol;
	}

	public void setPieChartCol(Column pieChartCol) {
		this.pieChartCol = pieChartCol;
	}

	public String getStackBarName() {
		return stackBarName;
	}

	public void setStackBarName(String stackBarName) {
		this.stackBarName = stackBarName;
	}

	public String getPieChartName() {
		return pieChartName;
	}

	public void setPieChartName(String pieChartName) {
		this.pieChartName = pieChartName;
	}

	public String getProjectStatus() {
		return projectStatus;
	}

	public void setProjectStatus(String projectStatus) {
		this.projectStatus = projectStatus;
	}

	public int getProfileFk() {
		return profileFk;
	}

	public void setProfileFk(int profileFk) {
		this.profileFk = profileFk;
	}
 
}