/*
 * This java source file is generated by DAO4J v1.16
 * Generated on Fri Mar 20 11:39:57 IST 2009
 * For more information, please contact b-i-d@163.com
 * Please check http://members.lycos.co.uk/dao4j/ for the latest version.
 */

package com.adams.dt.pojo;

import java.io.Serializable; 
import java.util.Date; 
/*
 * For Table chat
 */
public class Chat implements Serializable{

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;	
    
	protected int chatId;
	protected int senderId;    
	protected String senderName;
	protected String description;
	protected int receiverId;
	protected String receiverName;		
	protected Date chatDateentry;
	private int projectFk;
	
    public Chat() {
    }

	/**
	 * @return the chatId
	 */
	public int getChatId() {
		return chatId;
	}

	/**
	 * @param chatId the chatId to set
	 */
	public void setChatId(int chatId) {
		this.chatId = chatId;
	}
  
	/**
	 * @return the senderId
	 */
	public int getSenderId() {
		return senderId;
	}

	/**
	 * @param senderId the senderId to set
	 */
	public void setSenderId(int senderId) {
		this.senderId = senderId;
	}

	/**
	 * @return the senderName
	 */
	public String getSenderName() {
		return senderName;
	}

	/**
	 * @param senderName the senderName to set
	 */
	public void setSenderName(String senderName) {
		this.senderName = senderName;
	}

	/**
	 * @return the description
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * @param description the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * @return the receiverId
	 */
	public int getReceiverId() {
		return receiverId;
	}

	/**
	 * @param receiverId the receiverId to set
	 */
	public void setReceiverId(int receiverId) {
		this.receiverId = receiverId;
	}

	/**
	 * @return the receiverName
	 */
	public String getReceiverName() {
		return receiverName;
	}

	/**
	 * @param receiverName the receiverName to set
	 */
	public void setReceiverName(String receiverName) {
		this.receiverName = receiverName;
	}

	/**
	 * @return the chatDateentry
	 */
	public Date getChatDateentry() {
		return chatDateentry;
	}

	/**
	 * @param chatDateentry the chatDateentry to set
	 */
	public void setChatDateentry(Date chatDateentry) {
		this.chatDateentry = chatDateentry;
	}
	
	/**
	 * @return the projectFk
	 */
	public int getProjectFk() {
		return projectFk;
	}
	public void setProjectFk(int projectFk) {
		this.projectFk = projectFk;
	} 

}