/*
 * This java source file is generated by DAO4J v1.16
 * Generated on Fri Mar 20 11:39:50 IST 2009
 * For more information, please contact b-i-d@163.com
 * Please check http://members.lycos.co.uk/dao4j/ for the latest version.
 */

package com.adams.dt.pojo;

import java.io.Serializable; 
import java.util.Set;

/*
 * For Table groups
 */
public class DefaultTemplate implements Serializable {
	 
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	  /* group_ID, PK */
    protected int defaultTemplateId;  
    protected String defaultTemplateLabel;  
    protected int companyFK;
	public int getDefaultTemplateId() {
		return defaultTemplateId;
	}
	public void setDefaultTemplateId(int defaultTemplateId) {
		this.defaultTemplateId = defaultTemplateId;
	}
	public String getDefaultTemplateLabel() {
		return defaultTemplateLabel;
	}
	public void setDefaultTemplateLabel(String defaultTemplateLabel) {
		this.defaultTemplateLabel = defaultTemplateLabel;
	}
	public int getCompanyFK() {
		return companyFK;
	}
	public void setCompanyFK(int companyFK) {
		this.companyFK = companyFK;
	}  
}