/*
 * This java source file is generated by DAO4J v1.16
 * Generated on Fri Mar 20 11:39:57 IST 2009
 * For more information, please contact b-i-d@163.com
 * Please check http://members.lycos.co.uk/dao4j/ for the latest version.
 */

package com.adams.dt.pojo;

import java.io.Serializable;

public class FileTags implements Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	protected int filetagId;
	protected int fileFK;
	protected int tagFK;

	public FileTags() {

	}

	/**
	 * @return the filetagId
	 */
	public int getFiletagId() {
		return filetagId;
	}

	/**
	 * @param filetagId the filetagId to set
	 */
	public void setFiletagId(int filetagId) {
		this.filetagId = filetagId;
	}

	/**
	 * @return the fileFK
	 */
	public int getFileFK() {
		return fileFK;
	}

	/**
	 * @param fileFK the fileFK to set
	 */
	public void setFileFK(int fileFK) {
		this.fileFK = fileFK;
	}

	/**
	 * @return the tagFK
	 */
	public int getTagFK() {
		return tagFK;
	}

	/**
	 * @param tagFK the tagFK to set
	 */
	public void setTagFK(int tagFK) {
		this.tagFK = tagFK;
	} 

}