/*
 * This java source file is generated by DAO4J v1.16
 * Generated on Fri Mar 20 11:39:50 IST 2009
 * For more information, please contact b-i-d@163.com
 * Please check http://members.lycos.co.uk/dao4j/ for the latest version.
 */

package com.adams.dt.pojo;

import java.io.Serializable; 
import java.util.Set;

/*
 * For Table groups
 */
public class Impremiur implements Serializable {
	 
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	  /* group_ID, PK */
    protected int impremiurId;  
    protected int impremiurPerson;
    protected String impremiurLabel;
    protected Set<Presetstemplates> presetstemplateSet;
	 
	public Set<Presetstemplates> getPresetstemplateSet() {
		return presetstemplateSet;
	}
	public void setPresetstemplateSet(Set<Presetstemplates> presetstemplateSet) {
		this.presetstemplateSet = presetstemplateSet;
	}
	public int getImpremiurId() {
		return impremiurId;
	}
	public void setImpremiurId(int impremiurId) {
		this.impremiurId = impremiurId;
	}
	public String getImpremiurLabel() {
		return impremiurLabel;
	}
	public void setImpremiurLabel(String impremiurLabel) {
		this.impremiurLabel = impremiurLabel;
	}
	public int getImpremiurPerson() {
		return impremiurPerson;
	}
	public void setImpremiurPerson(int impremiurPerson) {
		this.impremiurPerson = impremiurPerson;
	} 
 
}