/*
 * This java source file is generated by DAO4J v1.16
 * Generated on Fri Mar 20 11:39:57 IST 2009
 * For more information, please contact b-i-d@163.com
 * Please check http://members.lycos.co.uk/dao4j/ for the latest version.
 */

package com.adams.dt.pojo;

import java.io.Serializable;  
import java.util.Date;
/*
 * For Table persons
 */
public class Persons implements Serializable{

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	public static final int ACTIVATED =1;
	/* Person_ID, PK */
    protected int personId;  
    protected int defaultProfile;
    private int companyFk;
    
    /* Person_Firstname */
    protected String personFirstname;

    /* Person_Lastname */
    protected String personLastname;

    /* Person_Email */
    protected String personEmail;

    /* Person_Login */
    protected String personLogin;

    /* Person_Password */
    protected String personPassword;
 
    /* Person_Position */
    protected String personPosition;

    /* Person_Phone */
    protected String personPhone;

    /* Person_Mobile */
    protected String personMobile;

    /* Person_Pict */
    protected byte[] personPict;

    /* Person_DateEntry */
    protected Date personDateentry;

    /* Activated */
    protected short activated;
    
    /* Person_ActiveChatid */
    protected String activeChatid;
    
    /* Person_LoginStatus */
    protected String loginStatus;
    protected String personAddress;
    protected String personPostalCode;
    protected String personCity;
    protected String personCountry;


    public String getPersonAddress() {
		return personAddress;
	}

	public void setPersonAddress(String personAddress) {
		this.personAddress = personAddress;
	}

	public String getPersonPostalCode() {
		return personPostalCode;
	}

	public void setPersonPostalCode(String personPostalCode) {
		this.personPostalCode = personPostalCode;
	}

	public String getPersonCity() {
		return personCity;
	}

	public void setPersonCity(String personCity) {
		this.personCity = personCity;
	}

	public String getPersonCountry() {
		return personCountry;
	}

	public void setPersonCountry(String personCountry) {
		this.personCountry = personCountry;
	}

	public Persons() {
    }

    /* Person_ID, PK */
    public int getPersonId() {
        return personId;
    }

    /* Person_ID, PK */
    public void setPersonId(int personId) {
        this.personId = personId;
    }

    /* Person_Firstname */
    public String getPersonFirstname() {
        return personFirstname;
    }

    /* Person_Firstname */
    public void setPersonFirstname(String personFirstname) {
        this.personFirstname = personFirstname;
    }

    /* Person_Lastname */
    public String getPersonLastname() {
        return personLastname;
    }

    /* Person_Lastname */
    public void setPersonLastname(String personLastname) {
        this.personLastname = personLastname;
    }

    /* Person_Email */
    public String getPersonEmail() {
        return personEmail;
    }

    /* Person_Email */
    public void setPersonEmail(String personEmail) {
        this.personEmail = personEmail;
    }

    /* Person_Login */
    public String getPersonLogin() {
        return personLogin;
    }

    /* Person_Login */
    public void setPersonLogin(String personLogin) {
        this.personLogin = personLogin;
    }

    /* Person_Password */
    public String getPersonPassword() {
        return personPassword;
    }

    /* Person_Password */
    public void setPersonPassword(String personPassword) {
        this.personPassword = personPassword;
    } 

    /* Person_Position */
    public String getPersonPosition() {
        return personPosition;
    }

    /* Person_Position */
    public void setPersonPosition(String personPosition) {
        this.personPosition = personPosition;
    }

    /* Person_Phone */
    public String getPersonPhone() {
        return personPhone;
    }

    /* Person_Phone */
    public void setPersonPhone(String personPhone) {
        this.personPhone = personPhone;
    }

    /* Person_Mobile */
    public String getPersonMobile() {
        return personMobile;
    }

    /* Person_Mobile */
    public void setPersonMobile(String personMobile) {
        this.personMobile = personMobile;
    }

    /* Person_Pict */
    public byte[] getPersonPict() {
        return personPict;
    }

    /* Person_Pict */
    public void setPersonPict(byte[] personPict) {
        this.personPict = personPict;
    }

    /* Person_DateEntry */
    public Date getPersonDateentry() {
        return personDateentry;
    }

    /* Person_DateEntry */
    public void setPersonDateentry(Date personDateentry) {
        this.personDateentry = personDateentry;
    }

    /* Activated */
    public short getActivated() {
        return activated;
    }

    /* Activated */
    public void setActivated(short activated) {
        this.activated = activated;
    }
    
    /* Person_ActiveChatid */
    public String getActiveChatid() {
        return activeChatid;
    }

    /* Person_ActiveChatid */
    public void setActiveChatid(String activeChatid) {
        this.activeChatid = activeChatid;
    }
    
    /* Person_LoginStatus */
    public String getLoginStatus() {
        return loginStatus;
    }

    /* Person_LoginStatus */
    public void setLoginStatus(String loginStatus) {
        this.loginStatus = loginStatus;
    }
 
	public static int getACTIVATED() {
		return ACTIVATED;
	}   
 

	public int getCompanyFk() {
		return companyFk;
	}

	public void setCompanyFk(int companyFk) {
		this.companyFk = companyFk;
	}

	public int getDefaultProfile() {
		return defaultProfile;
	}

	public void setDefaultProfile(int defaultProfile) {
		this.defaultProfile = defaultProfile;
	}
     
}